# 总之先整一个好像可以自动执行什么操作的这个玩玩好了。。。
# 目测这个文件应该可以实现的效果是在修改了之后自动把咱的友链进行更新

name: 添加友链

on:
  push:
    branches: [master]
    # paths : [Source/**]
  pull_request:
    branches: [master]
    # paths : [Source/**]

jobs:
  Check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1.2.0 # 不是很懂。。。。不过好像这样就算装好python3.x了。。。
    
    # - name: Pip Installer
      # uses: BSFishy/pip-action@v1
      # with:
        # 好像是说要把想装的pip的包都丢进去。。。但是现在好像不需要装什么包。。。
        # packages: # optional, default is
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: add Links
      run: python "$GITHUB_WORKSPACE/Source/python/addLinks.py" "$GITHUB_WORKSPACE"
    
